#! /bin/bash

# Author: Sergio contreras
# Date: 07/11/2024
# Description: This script will ping multiple remote hosts and notify
# Modified: 07/11/202

hosts="/workspaces/L2_App_Training/Bash/ps/myhosts"
for ip in $(cat $hosts)
	do
		ping -c1  $ip &> /dev/null
		if [ $? -eq 0 ]; then
			echo $ip is OK
		else
			echo $ip NOT OK
		fi
done

