#! /bin/bash

# Author: Sergio contreras
# Date: 07/11/2024
# Description: This script will ping a remote host and notify
# Modified: 07/11/202

hosts="127.0.0.53"
ping -c1  $hosts &> /dev/null
	if [ $? -eq 0 ]; then
		echo $hosts is OK
	else
		echo $hosts NOT OK
	fi

