#! /bin/bash
# Author: Sergio contreras
# Date: 07/11/2024
# Description: This script will pull only error messages from /var/log/history.log
# Modified: 07/11/2024

grep -i --color fail /workspaces/L2_App_Training/Bash/professional-scripts/*
